name: Build LaTeX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build LaTeX
    runs-on: ubuntu-latest
    container: texlive/texlive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Thesis
        run: latexmk -pdfxe ctufit-thesis.tex

      - name: Build Covers
        run: |
          latexmk -pdf covers/cover.tex
          latexmk -pdf covers/cover-inverse-colours.tex

      - name: Rename PDF Files
        run: |
          mv ctufit-thesis.pdf bp-paukert.pdf
          mv cover.pdf bp-paukert-desky.pdf
          mv cover-inverse-colours.pdf bp-paukert-desky-invert-barvy.pdf

      - name: Upload Thesis Files
        uses: actions/upload-artifact@v2
        with:
          name: bp-paukert-pdf
          path: ./*.pdf
